### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by colindaven** [bhofmei/jbplugin-hierarchicalcheckbox#2]
Hi, thanks for this.

The "activate" section contains a typo - extra space, it likely should read

[ plugins.HierarchicalCheckboxPlugin ]
location = plugins/HierarchicalCheckboxPlugin

instead of

[ plugins. HierarchicalCheckboxPlugin ]
location = plugins/HierarchicalCheckboxPlugin

**Comment by bhofmei** [comment]
Thanks for letting me know! I’ve fixed the issue now.
