### ISSUE TITLE
Not compatible with Apollo

### ISSUE THREAD

**Issue by hsiaoyi0504** [bhofmei/jbplugin-hierarchicalcheckbox#3]
When I tested on `JBrowse 1.12.3`, it works, but when I used the `Apollo 2.0.6` (also with `JBrowse 1.12.3` and it's automatically downloaded by `Apollo`. Plugin installation is by specifying setting in `apollo-config.groovy`) , it didn't work (no checkboxes show up).

I simply uncomment the line `console.log("plugin HierarchicalCheckboxPlugin constructor");` in `main.js` and it shows in console, so the plugin seems to be loaded, but for some reason it didn't work.

**Comment by bhofmei** [comment]
Thanks for using my plugin! I've never used Apollo, which is why I haven't noticed an issue before. I'll look into this as soon as I can.

**Comment by bhofmei** [comment]
i wanted to let you know I didn't forget about this. I've been having issues installing Apollo so I haven't been able to determine where the issue might be.

**Comment by hsiaoyi0504** [comment]
Thanks! It seems that it might not be the problem of your plugin. Refer to this GMOD/Apollo#1724.

**Comment by bhofmei** [comment]
Okay. Hopefully you can figure it out. I'm going to close this issue in the mean time since it's not an issue with this plugin.
